language: ruby

cache: bundler

bundler_args: --no-deployment --binstubs=./bin

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - rvm rubygems current
  - gem update --system || true
  - gem --version
  - source ./install-travis-bundler.sh
  - bundle ${MY_BUNDLER_VERSION} --version

install:
  - bundle ${MY_BUNDLER_VERSION} config --local jobs 3
  - bundle ${MY_BUNDLER_VERSION} config --local retry 3
  - bundle ${MY_BUNDLER_VERSION} config --local binstubs ./bin
  - bundle ${MY_BUNDLER_VERSION} config --local bin ./bin
  - bundle ${MY_BUNDLER_VERSION} install
  - gem env
  - bundle ${MY_BUNDLER_VERSION} env

script:
   - echo $BUNDLE_GEMFILE
   - bundle ${MY_BUNDLER_VERSION} exec rake

gemfile:
  - gemfiles/rails_4.0.0.gemfile
  - gemfiles/rails_4.1.1.gemfile
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_5.0.0.gemfile
  - gemfiles/rails_5.0.0.1.gemfile
  - gemfiles/rails_5.0.1.gemfile
  - gemfiles/rails_5.0.2.gemfile
  - gemfiles/rails_5.1.0.gemfile
  - gemfiles/rails_5.2.0.gemfile
  - gemfiles/rails_5.2.4.gemfile
  - gemfiles/rails_6.0.0.gemfile
  - gemfiles/rails_6.0.1.gemfile
matrix:
  fast_finish: true
  exclude:
  - rvm: 2.4.7
    gemfile: gemfiles/rails_4.0.0.gemfile
  - rvm: 2.4.7
    gemfile: gemfiles/rails_4.1.1.gemfile
  - rvm: 2.4.7
    gemfile: gemfiles/rails_4.2.0.gemfile
  - rvm: 2.5.6
    gemfile: gemfiles/rails_4.0.0.gemfile
  - rvm: 2.5.6
    gemfile: gemfiles/rails_4.1.1.gemfile
  - rvm: 2.5.6
    gemfile: gemfiles/rails_4.2.0.gemfile
  - rvm: 2.6.5
    gemfile: gemfiles/rails_4.0.0.gemfile
  - rvm: 2.6.5
    gemfile: gemfiles/rails_4.1.1.gemfile
  - rvm: 2.6.5
   gemfile: gemfiles/rails_4.2.0.gemfile
rvm:
  - 2.2.5
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.4.7
  - 2.5.6
  - 2.6.5
notifications:
  email: false
